language: python

python: 3.6

script: python main.py

before_deploy:
    - "./build.sh"

deploy:
    provider: lambda
    handler_name: "handler"
    module_name: "main"
    runtime: "python3.6"
    region: "us-east-1"
    function_name: "continuous_lambda"
    zip: lambda.zip
    publish: true
    role: "arn:aws:iam::578594301922:role/continuous_lambda_role"
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    access_key_id: $AWS_ACCESS_KEY_ID
