language: python

python: 3.6

env:
    - ENVIRONMENT=staging
    - ENVIRONMENT=production

script: python main.py

before_deploy:
    - "./build.sh"

deploy:
    provider: lambda
    handler_name: "handler"
    module_name: "main"
    runtime: "python3.6"
    region: "us-east-1"
    function_name: "$ENVIRONMENT_test_lambda_travis"
    zip: lambda.zip
    role: "arn:aws:iam::578594301922:role/lambda_basic_execution"
    secret_access_key:
        secure: Yx8DWJ9U92r+5UHgem8oQ84bOneK7K1f4dsqRItcMP5UkWrPFdeuGNMjjnXmyqNtVVrRM4BuK0MxfqxiiZs0ZU3WTTU73HJrBwg9qwDJYxfSjljqxXTf5d58ztNnbpNw1L80+v6v/rv4hmbHbdWWg9ajmO4/CHbSBWbFiUt9RFBVgjvigbikRidscgGcDvCewwbs1JR+rKvuwFNq4rYK6Z/c12AtsrR5a69NQRs7xrJfMz8lYpC2hT0oX9NyNzaLhqxUa6FCBVfTmJuMEXZ+J5oc9NWnIGQ7PpFrzRh9pMbPQ0BrrRrMxX+Pc1DJDAMfASaIZNkp9IxTCH0odYxt4VztHXiAitU/OFva8GMltFqqHoksTJdJgK75ALPkg6h1hD1OGQxwhO/NMhzzKII2Vl1uLkygL7z0CtTaU/1aJxTrkpSU040Z/ya6ZdoZeQixWwZZHAx/+ljF1Kv3cOms1CCr4kPtjliiqkqqnc0i+vKk1UMPBr2HC+cdjhOkf6M+kB4oN9DDDR+pOoKseLIZENQUZMI1CBTh6ITblGBZ+6oFd3/IgFGGS+UtXTzV2xXBOY6P4pZ4uY88yxtPL1t60EvP4WtPZqijusdLq9HX1MNbcvF6pFi6o4iQZ9w41mp80PBCirYNH55jcUrSUA40bJYbsjAAe5PmUXMukk5dv2M=
    access_key_id:
        secure: 2OuaGe00mxb6qiQ7OaM4sls430992fhcVYjHRtt34GguJsuQdNxNB1ujcgzIdsmlnBvgTqoBWpaQVxjZOePOp43R9RFDzcapFLxME6H0JXBKjFI+gE69ZmjKXa2B9bVaijnlfFYqfH6dByTA+UBh9yyYt+FI6E1rAc4CEiS9lTMvDqVssbRCjeIQVNKuo0wX29EwZFcfoNOjg7vAqOC7rMV4qSJQFwSOKqr0jvutL3tm9bAoFAVXrNtW/mBLCizSF5XZITQDDNuADt+fdp8ITeDxhhAFs2w3VRWOZL3VJvXoxbDDbbnnwOuz8WpH/8JfMCIZyoYYst+Vi+TtEn3lZrW3y5fJpODVAyKY9XtLzv3JVdA9i0MIXWImSj/xbqRO0gm549fQw+GRn12B6TnWwa06zQBje2tvFr8PIMG7cXOxDChqiaPNCZVRJSR4AaoQ6Cc++M6HqpiIhbnnIOt3+pAwgKVmYDAmDiwobfUM/FvMxTbyR0kt/q/IBgxFMqvZrT1wL+cf63GR12TwoUYex4ebZWRmpLOIKApSvJ/eme0soGmD9vKnVggAuLkHaz86VhczBRzfpBb098OQJ1xtPBTv5Yj5WoMrICw481R0abiA9hrEfJiQNRlQ2+nkTeMMZYVzndj9iS3pUMlbgcSmWC+l6eU9icoCGm0Q539J+oU=
